version: '3.8'

services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gamelogger
    ports:
      - "3306:3306"

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      target: release_image
    environment:
      MYSQL_HOST: mysqldb
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"

networks:
  my-network: